"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['data_load_gui.py']
DATA_FILES = ['url_keys.json']
OPTIONS = {'argv_emulation': True,
           'iconfile': 'icon.png'}


setup(
    app=APP,
    data_files=DATA_FILES,
    py_modules=['json_load_methods','LWH_dataload','residence_ids'],
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
